/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.Messages.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.MoveitTutorials
{
    public class PlanPathGoal : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "moveit_tutorials/PlanPathGoal";

        // goal definition
        public Pose[] waypoints;

        public PlanPathGoal()
        {
            this.waypoints = new Pose[0];
        }

        public PlanPathGoal(Pose[] waypoints)
        {
            this.waypoints = waypoints;
        }
    }
}
