/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.MoveitTutorials
{
    public class RegisterSceneObjectToMoveitGoal : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "moveit_tutorials/RegisterSceneObjectToMoveitGoal";

        // goal definition
        public string[] names;
        public double[] positions_x;
        public double[] positions_y;
        public double[] positions_z;
        public double[] orientations_x;
        public double[] orientations_y;
        public double[] orientations_z;
        public double[] orientations_w;
        public double[] sizes_x;
        public double[] sizes_y;
        public double[] sizes_z;
        public byte[] mesh;

        public RegisterSceneObjectToMoveitGoal()
        {
            this.names = new string[0];
            this.positions_x = new double[0];
            this.positions_y = new double[0];
            this.positions_z = new double[0];
            this.orientations_x = new double[0];
            this.orientations_y = new double[0];
            this.orientations_z = new double[0];
            this.orientations_w = new double[0];
            this.sizes_x = new double[0];
            this.sizes_y = new double[0];
            this.sizes_z = new double[0];
            this.mesh = new byte[0];
        }

        //public RegisterSceneObjectToMoveitGoal(string[] names, double[] positions_x, double[] positions_y, double[] positions_z, double[] orientations_x, double[] orientations_y, double[] orientations_z, double[] orientations_w, double[] sizes_x, double[] sizes_y, double[] sizes_z, char[] mesh)
        //{
        //    this.names = names;
        //    this.positions_x = positions_x;
        //    this.positions_y = positions_y;
        //    this.positions_z = positions_z;
        //    this.orientations_x = orientations_x;
        //    this.orientations_y = orientations_y;
        //    this.orientations_z = orientations_z;
        //    this.orientations_w = orientations_w;
        //    this.sizes_x = sizes_x;
        //    this.sizes_y = sizes_y;
        //    this.sizes_z = sizes_z;
        //    this.mesh = mesh;
        //}
    }
}
