/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.Messages.Standard;
using RosSharp.RosBridgeClient.MessageTypes.Actionlib;

namespace RosSharp.RosBridgeClient.MessageTypes.MoveitTutorials
{
    public class RegisterSceneObjectToMoveitActionGoal : ActionGoal<RegisterSceneObjectToMoveitGoal>
    {
        [JsonIgnore]
        public const string RosMessageName = "moveit_tutorials/RegisterSceneObjectToMoveitActionGoal";

        public RegisterSceneObjectToMoveitActionGoal() : base()
        {
            this.goal = new RegisterSceneObjectToMoveitGoal();
        }

        public RegisterSceneObjectToMoveitActionGoal(Header header, GoalID goal_id, RegisterSceneObjectToMoveitGoal goal) : base(header, goal_id)
        {
            this.goal = goal;
        }
    }
}
